import { Customer, Lead, Deal, Task, Activity, User, NotificationItem } from './types';

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Acme Corp',
    domain: 'acmecorp.io',
    logoText: 'AC',
    logoBg: 'bg-blue-100 text-blue-700 border-blue-200',
    status: 'Active',
    industry: 'Enterprise Software',
    mainContact: {
      name: 'Sarah Jenkins',
      email: 's.jenkins@acmecorp.io',
      phone: '+1 (555) 019-2834',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    totalValue: 124500,
    lastActivity: '2 hrs ago',
    accountOwner: {
      name: 'Michael Johnson',
      avatarText: 'MJ',
    },
    arr: 124500,
    renewalDate: 'Oct 15, 2024',
    tags: ['High Priority', 'Q4 Target', 'Enterprise'],
    healthScore: 85,
    healthTrend: '+5 this month',
    location: 'San Francisco, CA',
  },
  {
    id: 'cust-2',
    name: 'Global Industries',
    domain: 'globalind.net',
    logoText: 'G',
    logoBg: 'bg-purple-100 text-purple-700 border-purple-200',
    status: 'Onboarding',
    industry: 'Manufacturing',
    mainContact: {
      name: 'Michael T.',
      email: 'm.taylor@globalind.net',
      phone: '+1 (555) 022-9911',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    totalValue: 89200,
    lastActivity: 'Yesterday',
    accountOwner: {
      name: 'Sarah Jenkins',
      avatarText: 'SJ',
    },
    arr: 89200,
    renewalDate: 'Nov 30, 2024',
    tags: ['Onboarding', 'Mid-Market'],
    healthScore: 72,
    healthTrend: '+2 this month',
    location: 'Chicago, IL',
  },
  {
    id: 'cust-3',
    name: 'Stark Systems',
    domain: 'starksys.io',
    logoText: 'S',
    logoBg: 'bg-red-100 text-red-700 border-red-200',
    status: 'At Risk',
    industry: 'Defense',
    mainContact: {
      name: 'Pepper R.',
      email: 'p.potts@starksys.io',
      phone: '+1 (555) 033-4455',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    },
    totalValue: 450000,
    lastActivity: '5 days ago',
    accountOwner: {
      name: 'David Chen',
      avatarText: 'DC',
    },
    arr: 450000,
    renewalDate: 'Dec 12, 2024',
    tags: ['At Risk', 'Enterprise', 'Strategic'],
    healthScore: 48,
    healthTrend: '-12 this month',
    location: 'New York, NY',
  },
  {
    id: 'cust-4',
    name: 'Wayne Ent.',
    domain: 'wayne.co',
    logoText: 'W',
    logoBg: 'bg-teal-100 text-teal-700 border-teal-200',
    status: 'Active',
    industry: 'Finance',
    mainContact: {
      name: 'Lucius F.',
      email: 'l.fox@wayne.co',
      phone: '+1 (555) 044-8899',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
    totalValue: 1200000,
    lastActivity: '1 hr ago',
    accountOwner: {
      name: 'Michael Johnson',
      avatarText: 'MJ',
    },
    arr: 1200000,
    renewalDate: 'Jan 15, 2025',
    tags: ['Key Account', 'Enterprise', 'Expansion Target'],
    healthScore: 94,
    healthTrend: '+8 this month',
    location: 'Gotham, NY',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    title: 'Acme Corp Expansion',
    contactName: 'Sarah Jenkins',
    date: 'Today',
    score: 85,
    status: 'New Leads',
    owner: 'Sarah Jenkins',
    isHot: true,
  },
  {
    id: 'lead-2',
    title: 'Apex Dynamics',
    contactName: 'Carlos Rossi',
    date: 'Today',
    score: 78,
    status: 'New Leads',
    owner: 'Marcus Rodriguez',
  },
  {
    id: 'lead-3',
    title: 'Vortex Cloud Pilot',
    contactName: 'Elena Rostova',
    date: 'Yesterday',
    score: 64,
    status: 'New Leads',
    owner: 'Elena Jackson',
  },
  {
    id: 'lead-4',
    title: 'Global Tech Upgrade',
    contactName: 'Michael Chang',
    date: 'Yesterday',
    score: 62,
    status: 'Contacted',
    owner: 'Michael Johnson',
  },
  {
    id: 'lead-5',
    title: 'Horizon Media Sync',
    contactName: 'Jessica Alba',
    date: '3 days ago',
    score: 71,
    status: 'Contacted',
    owner: 'Sarah Jenkins',
  },
  {
    id: 'lead-6',
    title: 'Stark Ind. Q3 Need',
    contactName: 'Tony Stark',
    date: '2 days ago',
    score: 92,
    status: 'Qualified',
    owner: 'Marcus Rodriguez',
    isHot: true,
  },
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-1',
    title: 'Acme Corp Redesign',
    company: 'Acme Corp',
    amount: 45000,
    priority: 'Medium',
    stage: 'Prospect',
    dueDate: 'Oct 12',
    owner: {
      name: 'Marcus Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'deal-2',
    title: 'Stark Industries ERP',
    company: 'Stark Systems',
    amount: 120000,
    priority: 'High',
    stage: 'Prospect',
    dueDate: 'Nov 01',
    owner: {
      name: 'Sarah Jenkins',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'deal-3',
    title: 'Globex Cloud Migration',
    company: 'Globex Inc',
    amount: 35000,
    priority: 'Low',
    stage: 'Qualified',
    dueDate: 'Oct 20',
    owner: {
      name: 'John Doe',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'deal-4',
    title: 'Wayne Ent Security Setup',
    company: 'Wayne Ent.',
    amount: 210000,
    priority: 'High',
    stage: 'Proposal',
    dueDate: 'Sep 30',
    owner: {
      name: 'Elena Jackson',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    },
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-p1',
    name: 'Finalize Acme Corp SLA Proposal',
    deal: 'Acme Corp Redesign',
    priority: 'High',
    dueDate: 'Today',
    dueStatus: 'Due Today',
    assignee: {
      name: 'Sarah Jenkins',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    progress: 80,
    completed: false,
    isHighPriorityCard: true,
  },
  {
    id: 'task-p2',
    name: 'Follow up on TechNova Q3 Budget',
    deal: 'TechNova Expansion',
    priority: 'High',
    dueDate: 'Yesterday',
    dueStatus: 'Overdue (1d)',
    assignee: {
      name: 'Marcus Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    progress: 30,
    completed: false,
    isHighPriorityCard: true,
  },
  {
    id: 'task-1',
    name: 'Draft Integration Specs',
    deal: 'Globex API Sync',
    priority: 'Medium',
    dueDate: 'Oct 24, 2023',
    assignee: {
      name: 'Sarah Jenkins',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    progress: 45,
    completed: false,
  },
  {
    id: 'task-2',
    name: 'Send Contract for Review',
    deal: 'Wayne Ent. Licensing',
    priority: 'High',
    dueDate: 'Oct 25, 2023',
    assignee: {
      name: 'Michael Johnson',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
    progress: 10,
    completed: false,
  },
  {
    id: 'task-3',
    name: 'Prepare Q4 Deck',
    deal: 'Internal',
    priority: 'Low',
    dueDate: 'Oct 20, 2023',
    assignee: {
      name: 'David Chen',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    },
    progress: 100,
    completed: true,
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    type: 'call',
    author: 'Sarah Jenkins',
    target: 'Acme Corp',
    title: 'Sarah Jenkins logged a call with Acme Corp.',
    content: 'Discussed Q3 expansion timeline and deployment dates with engineering leadership.',
    time: '2 hours ago',
  },
  {
    id: 'act-2',
    type: 'email',
    author: 'David Lee',
    target: 'Globex Inc',
    title: 'David Lee sent a proposal to Globex Inc.',
    content: 'Hi Sarah, just checking in to see if you had a chance to review the updated proposal sent last week.',
    time: '4 hours ago',
  },
  {
    id: 'act-3',
    type: 'stage_change',
    author: 'Michael Johnson',
    target: '#4920',
    title: 'Deal #4920 moved to Closed Won.',
    content: 'Michael Johnson moved deal Acme Q3 Expansion to Negotiation.',
    time: 'Yesterday',
    dealName: 'Acme Q3 Expansion',
    newStage: 'Negotiation',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@nexuscrm.com',
    role: 'Admin',
    team: 'Product',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastActive: 'Just now',
  },
  {
    id: 'usr-2',
    name: 'Marcus Rodriguez',
    email: 'marcus.r@nexuscrm.com',
    role: 'Sales Rep',
    team: 'Enterprise Sales',
    status: 'Active',
    avatarText: 'MR',
    lastActive: '2 hours ago',
  },
  {
    id: 'usr-3',
    name: 'David Chen',
    email: 'd.chen@nexuscrm.com',
    role: 'Manager',
    team: 'Customer Success',
    status: 'Pending',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    lastActive: 'Never',
  },
  {
    id: 'usr-4',
    name: 'Alicia Woods',
    email: 'alicia.w@nexuscrm.com',
    role: 'Support',
    team: 'Customer Success',
    status: 'Deactivated',
    avatarText: 'AW',
    lastActive: 'Oct 12, 2023',
  },
  {
    id: 'usr-5',
    name: 'Elena Jackson',
    email: 'elena.j@nexuscrm.com',
    role: 'Sales Rep',
    team: 'Enterprise Sales',
    status: 'Active',
    avatarText: 'EJ',
    lastActive: '1 day ago',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'mention',
    category: 'Mentions',
    title: 'Sarah Jenkins mentioned you in Q3 Marketing Strategy',
    body: '"Can you review the latest projections for the European market? I think we might need to adjust the spend."',
    time: '10 min ago',
    read: false,
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'notif-2',
    type: 'system',
    category: 'System',
    title: 'Data synchronization paused',
    body: 'The Salesforce integration sync has been temporarily paused due to API limits. It will resume in 45 minutes.',
    time: '1 hour ago',
    read: false,
    iconName: 'cloud_sync',
  },
  {
    id: 'notif-3',
    type: 'deal',
    category: 'Unread',
    title: 'Deal Won: Acme Corp Enterprise License',
    body: "Michael Chang moved this deal to 'Closed Won'. Total value: $45,000.",
    time: '3 hours ago',
    read: true,
    iconName: 'monetization_on',
  },
  {
    id: 'notif-4',
    type: 'task',
    category: 'Unread',
    title: 'David Chen assigned you a task: Prepare Q4 Slide Deck',
    body: 'Due by Friday at 5:00 PM.',
    time: 'Yesterday',
    read: true,
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];
